### PR TITLE
Parsed satoshi core txvalidjson tests

### PR DESCRIPTION
**Pull request by tphyahoo**
parses test description in json, gives better feedback in tests.

### CODE REVIEW

**Comment by tphyahoo** [comment]
btw, I do feel a little funny about the number of commits.  Especially as it seems to me some of this history should already have been merged into master.  

I attempted to follow advice xenog gave here:

https://github.com/haskoin/haskoin/pull/250#issuecomment-184702298

but rebase haskoin/master gave conflicts, and the merge conflict resolutions offered seems to have deleted some of my work.  So I gave up on the rebase approach for now.

The other thing I considered doing was starting a new branch from master, and doing a checkout of the only file with changes, and pushing this single clean change.  But then all the history gets lost, and logically this was continuation of changes I have already done, so it seems to make more sense to keep it all on one branch.

Any advice is appreciated.

**Comment by jprupp** [comment]
Try to rebase against master first:

```
git remote add upstream https://github.com/haskoin/haskoin.git
git fetch upstream
git checkout <your-branch>
git rebase upstream/master
```

This is likely to cause some commits not to apply cleanly. You must fix all issues by looking at the problems:

```
git status
```

When editing files that have issues, look for sections contained between "<<<<<" and ">>>>>" lines. They show the conflicts. Read them carefully and correct the code, leaving only the correct version of changes. When done, add the conflicted files and continue rebasing:

```
git add -- <conflicted-file> <another-conflicted-file> [...]
git rebase --continue
```

When all commits have been applied, you can rebase again interactively and squash commits:

```
git rebase -i upstream/master
```

Change "pick" to "squash" for all commits but the topmost. If you have rebased already as shown above before doing this. there should not be any conflicts, and you'll be left with a single commit. When you save the file, you'll have to choose a commit message. You can delete the whole contents of the buffer and write a message that makes sense for the whole group of commits.

If you still have issues, I can do this work for you myself later.

Greetings

**Comment by tphyahoo** [comment]
I followed the procedure described, and I understand how to resolve merge-conflicted files.

The trouble is, 

1) none of the options in this merge-conflicted file include my most recent changes, in at least one instance.  I could fix this manually, but since git appears not to be working as advertising, it makes me paranoid that I'm missing something else.

2) I went ahead and tried to move forward regardless, and git refused rebase --continue even then.

```
➜  haskoin-core git:(55077a7) git status
rebase in progress; onto 55077a7
You are currently rebasing branch 'parsed_satoshi_core_txvalidjson_tests' on '55077a7'.
  (all conflicts fixed: run "git rebase --continue")

nothing to commit, working directory clean
➜  haskoin-core git:(55077a7) git rebase --continue
Applying: transaction unit tests: type sigs, comments
No changes - did you forget to use 'git add'?
If there is nothing left to stage, chances are that something else
already introduced the same changes; you might want to skip this patch.

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
```

So, I'm thinking I hit a git bug and it's probably time to throw in the towel and start a new branch.

I'll close this and do that.

**Comment by tphyahoo** [comment]
In case it's not obvious, I did do git add on the conflicted file, after resolving the conflicts.

**Comment by jprupp** [comment]
When you find yourself with no changes, you will not be able to continue rebasing, but you must skip the current commit. This happens because I merged some if your changes to master, when you opened this pull request earlier. But these changes have been merged as a single commit. Your system is detecting that some commits in your branch are not changing anything. In this case `git status` will reveal that the current commit performs no change.

You may continue using:

```
git rebase --skip
```

**Comment by tphyahoo** [comment]
This still leaves the issue that changes I made didn't appear in the merge conflict file.

**Comment by tphyahoo** [comment]
I am trying again though, I think I am starting to understand better how this works.

**Comment by tphyahoo** [comment]
I give up.  I understand the rebase + squash process better now, but it's just turned into a mess that doesn't seem worth maintaining history on.  Please accept #268 instead.

**Pull request closed without merging**
