### PR TITLE
Split test bench pkgs

### PR DESCRIPTION
**Pull request by wraithm**

### CODE REVIEW

**Comment by jprupp** [comment]
Haskoin is being used in production. This kind of pull request is too large, and could cause quite a bit of disruption to allow it to be merged by mistake into the master branch. I've revoked the ability to merge pull requests to anyone but original authors @plaprade and @jprupp to prevent accidental merges.

**Comment by wraithm** [comment]
@jprupp. Hey, sorry, this was an accident meant for a totally different repository.

**Comment by wraithm** [comment]
Won't happen again. I've deleted the relationship of our forks to this repo.

**Comment by jprupp** [comment]
I figured. It's a nice fork you have there. If you need any help or clarifications with any obscure code or thing you encounter, fire an email my way, and I'll do my best to help sort it out.

**Pull request closed without merging**
