### PR TITLE
Support for spending standard segwit transactions

### PR DESCRIPTION
**Pull request by GambolingPangolin**
This PR implements 
1. the signing algorithm for spending standard segwit (and p2sh-nested segwit) outputs,
2. validation code to cover these cases, and
3. a high level representation of witness data and auxiliary functions for working with it.

In addition, I also fixed a few typos and broke the transaction builder module up.

### CODE REVIEW

**Comment by GambolingPangolin** [comment]
This should address #379

**Comment by jprupp** [comment]
Wow @GambolingPangolin, that's quite the pull request, and your code looks very good. I will have to review this one deeply, and I'll try to get @plaprade involved as well, as he wrote most of the original signing code. Thank you very much.

**Comment by jprupp** [comment]
Thank you @GambolingPangolin, all your changes are very welcome.

**Comment by GambolingPangolin** [comment]
My pleasure!  I hope to have the opportunity to contribute more :grinning:

**Pull request merged**
