### PR TITLE
clean up testing code for bip32 wallets (tests_chain_in_vector)

### PR DESCRIPTION
**Pull request by tphyahoo**
This would be an easy merge after 

find_some_failcases_for_xkey_parsePath

is merged into master.

It doesn't add new functionality or change behavior, just simplifies  testing code.

The biggest improvement is it stops intertwingling the logic for the derivation path in testing vector, and puts everything into one places for testing, pretty much following the bip32 spec.

### CODE REVIEW

**Comment by jprupp** [comment]
Thanks for this pull request, I will review with @plaprade.

**Comment by tphyahoo** [comment]
this is ready to pull now (against the latest master).

If there's anything else I need to do to prep this, let me know and I'll try to make it ready.

I remember being a little confused about the desired merge strategy.

I'm still working on the fix for the three new failing tests.

Should have something fairly soon.

**Comment by jprupp** [comment]
Hello @tphyahoo,

We will merge all your BIP-32 changes in one single pull request. When you are done with these, create a new pull request for your entire BIP-32 changes. If possible squash all your commits into a single one. You may want to call it “Improved BIP-32 handling”, for example.

The pull request must leave the code in a consistent state and all tests passing after it is applied. If you do not know how to squash commits, you may want to look at the Git documentation, or I can do it while merging the code.

Do not forget to close this and the other two pull requests that you opened, as they are all related to BIP-32, before opening the new one.

Cheers, and thanks for this. It looks very good.

**Comment by tphyahoo** [comment]
superceded by #200.

**Comment by tphyahoo** [comment]
reopening since #200 is no-pull.

**Comment by tphyahoo** [comment]
this PR includes #189, which in turn includes PR #188.

So I'll start here and hopefully yield to a PR that gets the other 2 for free, rebased to current master

**Comment by tphyahoo** [comment]
locally, this builds cleanly and fails 3 tests, which is expected. (Tests for hard follows soft paths).

There are only two files affected, so it's a much more tractable PR than #200.

I will now create  a 1-commit PR with a merge --squash as I did with #200, and PR that pointing back to here.

**Pull request closed without merging**
