### PR TITLE
Upgrade deepseq to >=1.4

### PR DESCRIPTION
**Pull request by nuttycom**
See #175

### CODE REVIEW

**Comment by xenog** [comment]
ACK

**Comment by jprupp** [comment]
We use Stack and LTS Haskell to compile Haskoin. We can push the upper bound for deepseq, but not the lower bound, since deepseq 1.4 is not yet in the latest LTS Haskell.

**Comment by m0dev76** [comment]
We just merged in a pull request that moved most of the node to the haskoin-node project to simplify dependencies in haskoin. Some of your changes would now be in haskoin-node. 

Additionally, I think that if we decide to provide Generic instances for some types in the haskoin library, we should provide them for all the useful types that are exposed. It would make sense from a consistency point of view. That is at least what we try to do for other instances such as Json and NFData even though we might be missing quite a few.

**Comment by jprupp** [comment]
Hello @nuttycom,

In order to merge this pull request, we would like to get Generic instances for all exposed data types, instead of just a few of them, and also rebase against the latest master. Wolud you do this?

Cheers!

**Comment by nuttycom** [comment]
Sure, I can do this. It may take me a few days to get to it. Thanks for the
LTS upgrade!

**Comment by jprupp** [comment]
Send new pull request when done. I'll close this one.

**Pull request closed without merging**
