### PR TITLE
Fix truncating String to ByteString conversion

### LINKED ISSUE #184: Base58 malleability vulnerability due to ByteString conversion
The function `stringToBS` is implemented as `Data.ByteString.Char8.pack`, which truncates characters longer than 8 bits.  This means that a `String` may have unexpected `Base58` encoding.

### PR DESCRIPTION
**Pull request by jprupp**
Fixes #184.

### CODE REVIEW

**Comment by m0dev76** [comment]
I've been phasing out the use of `bsToString` and `stringToBS` because they were simply aliases to Char8.pack and Char8.unpack. I have been using the later versions in most of the newer code, especially the wallet. 

I am unsure if these functions are used anywhere in the network protocol path and if anything would break if we now decode results from the network as UTF8. This needs to be double checked.

**Comment by m0dev76** [comment]
Actually, I would rather advocate for removing those two functions entirely and use the appropriate conversions where necessary. We can also keep those two functions (the UTF8 variants) but renamed them such that their function is clearer. This will force us to go through the code and change all the instances of `bsToString` and `stringToBS`.

**Comment by jprupp** [comment]
I agree.  I have a ticket open for that.  I will do it.  For now, since this is a potential security issue, I'll merge this quick dirty fix, if you ack it.

**Comment by jprupp** [comment]
This request will be superseded.

**Pull request closed without merging**
